### ISSUE TITLE
`getDerivedStateFromProps` nulls state

### ISSUE THREAD

**Issue by supersonicclay** [fusionjs/fusion-react#157] opened 2018-08-27 20:54 UTC
### Type of issue
Bug

### Current behavior

Returning `null` from `getDerivedStateFromProps` sets `this.state` to `null`.

### Expected behavior

Returning `null` from `getDerivedStateFromProps` should not change state.

### Steps to reproduce

```
class MyComponent extends React.Component {
  state = {
    email: 'me@here.com'
  }

  static getDerivedStateFromProps() { return null; }

  render() {
    return (<div>{this.state.email}</div>); // should be 'me@here.com'
  }
}
```

### Your environment

* fusion-react version: 1.2.1 (issue does not exist in v1.1.0)

**Comment by supersonicclay** [comment] 2018-08-27 21:01
And disabling SSR via https://github.com/fusionjs/fusion-react/issues/95#issuecomment-399980523 did not fix the issue

**Comment by KevinGrandon** [comment] 2018-08-27 21:52
I tried adding a failing test case for this in https://github.com/fusionjs/fusion-react/pull/159 but was unable to reproduce. Needs further investigation.

**Comment by supersonicclay** [comment] 2018-08-27 22:32
You're using `constructor`. My repro uses a class field declaration.

**Comment by KevinGrandon** [comment] 2018-08-27 23:38
> You're using constructor. My repro uses a class field declaration.

Constructors assignment and class properties are essentially the same. I tried both in the test case and it didn't work, might have to reproduce with your real-world application.

**Comment by lhorie** [comment] 2018-10-11 21:18
This is fixed by https://github.com/fusionjs/fusion-react/pull/181

**Closed** 2018-10-11 21:18 UTC
